# Generated by Django 4.2.6 on 2023-12-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, null=True)),
                ('product_description', models.CharField(max_length=300, null=True)),
                ('product_price', models.FloatField(max_length=30, null=True)),
                ('category', models.CharField(choices=[('Fashion', 'Fashion'), ('Electronics', 'Electronics'), ('Food', 'Food'), ('Cosmatics', 'Cosmatics')], max_length=200, null=True)),
            ],
        ),
    ]
