# Generated by Django 4.2.6 on 2023-12-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_images',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
