# Generated by Django 4.2.6 on 2023-12-01 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flyerapp', '0004_alter_products_product_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flyerapp.products')),
            ],
        ),
    ]
