# Generated by Django 4.2.6 on 2023-12-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyerapp', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_images',
            field=models.FileField(null=True, upload_to='static/dbfl'),
        ),
    ]
